FROM node:14.15.5-stretch-slim as build

ENV NODE_ENV production

WORKDIR /app

#COPY node_modules .
COPY . ./

RUN npm install && npm run build && npm prune --production

FROM node:14.15.5-alpine3.13
ENV NODE_ENV production
WORKDIR /app

COPY --from=build "/app/node_modules" "/app/node_modules"
COPY --from=build "/app/build" "/app/build"
COPY --from=build "/app/scripts" "/app/scripts"

USER node
EXPOSE 9000

#CMD [ "npm", "run", "prodServer" ]
CMD [ "node", "./scripts/prodServer.js" ]

