apiVersion: apps/v1
kind: Deployment

metadata:
  name: excel-education-sis-frontend-sis-frontend-admin
  labels:
    app: excel-education-sis-frontend-sis-frontend-admin

spec:
  selector:
    matchLabels:
      app: excel-education-sis-frontend-sis-frontend-admin
  template:
    metadata:
      labels:
        app: excel-education-sis-frontend-sis-frontend-admin

    spec:
      containers:
        - name: nginx
          image: docker.git.sarvika.com/excel-education/sis/frontend/sis-frontend-admin:nginx-devel
          imagePullPolicy: Always
          ports:
            - containerPort: 80
        - name: admin-dashboard
          image: docker.git.sarvika.com/excel-education/sis/frontend/sis-frontend-admin:devel
          imagePullPolicy: Always
          env:
            - name: GENERATE_SOURCEMAP
              value: "true"
            - name: ENVIRONMENT
              value: staging
          ports:
            - containerPort: 9000
