export const ERROR_CODES_400S = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  ACCESS_DENIED: 'ACCESS_DENIED',
  ERR_EMPTY_VALUE: 'ERR_EMPTY_VALUE',
  NOT_FOUND: 'NOT_FOUND',
  ERR_FILE_MAX: 'ERR_FILE_MAX',
  ERR_FILE_TYPE: 'ERR_FILE_TYPE',
  ERR_BOOLEAN: 'ERR_BOOLEAN',
  ERR_EMAIL_FORMAT: 'ERR_EMAIL_FORMAT',
  ERR_NULL_VALUE: 'ERR_NULL_VALUE',
  ERR_UNIQUE: 'ERR_UNIQUE',
  ERR_DUPLICATE_ALIAS: 'ERR_DUPLICATE_ALIAS',
  ERR_DUPLICATE_COURSE_IN_SUBJECT: 'ERR_DUPLICATE_COURSE_IN_SUBJECT',
  ERR_EXPRESSION_MISMATCH: 'ERR_EXPRESSION_MISMATCH',
  ERR_MAX_VALUE: 'ERR_MAX_VALUE',
  ERR_MIN_VALUE: 'ERR_MIN_VALUE',
  ERR_INVALID_SLUG: 'ERR_INVALID_SLUG',
  ERR_EMPTY_META_TYPE: 'ERR_EMPTY_META_TYPE',
  ERR_DISTRICT_NOT_FOUND: 'ERR_DISTRICT_NOT_FOUND',
  ERR_MAX_SIZE: 'ERR_MAX_SIZE',
  ERR_INVALID_FILE_EXTENSION: 'ERR_INVALID_FILE_EXTENSION',
  ERR_SCHOOL_NOT_FOUND: 'ERR_SCHOOL_NOT_FOUND',
  ERR_PROGRAM_CATEOGRY_NOT_FOUND: 'ERR_PROGRAM_CATEOGRY_NOT_FOUND',
  ERR_AFTER: 'ERR_AFTER',
  ERR_ALPHA_DASH: 'ERR_ALPHA_DASH',
  ERR_DATE: 'ERR_DATE',
  ERR_DATE_FORMAT: 'ERR_DATE_FORMAT',
  ERR_DIGITS: 'ERR_DIGITS',
  ERR_NUMBER_MIN: 'ERR_NUMBER_MIN',
  ERR_STRING_MIN: 'ERR_STRING_MIN',
  ERR_NUMBER: 'ERR_NUMBER',
  ERR_INVALID_FORMAT: 'ERR_INVALID_FORMAT',
  VALUE_MUST_SAME_AS: 'VALUE_MUST_SAME_AS',
  ERR_INVALID_TENANT: 'ERR_INVALID_TENANT',
  ERR_INVALID_TENANT_ACCESS: 'ERR_INVALID_TENANT_ACCESS',
  ERR_INVALID_VALUE: 'ERR_INVALID_VALUE',
  INVALID_VALUE_CONTAINS_NAME: 'INVALID_VALUE_CONTAINS_NAME',
  NOT_EXISTS_IN_DB: 'NOT_EXISTS_IN_DB',
  BAD_USERNAME: 'BAD_USERNAME',
  ERR_USER_EXISTS: 'ERR_USER_EXISTS',
  ERR_MAX_SCHOOLS_IN_DISTRICT: 'ERR_MAX_SCHOOLS_IN_DISTRICT',
  ERR_ENTITY_NOT_FOUND: 'ERR_ENTITY_NOT_FOUND',
  ERR_COURSE_EXISTS_IN_PROGRAM: 'ERR_COURSE_EXISTS_IN_PROGRAM',
  ERR_FOREIGN_CONSTRAINT: 'ERR_FOREIGN_CONSTRAINT',
  ERR_PROGRAM_EXPIRED: 'ERR_PROGRAM_EXPIRED',
  ERR_MIN_AGE: 'ERR_MIN_AGE',
  ERR_NUMBER_OF_COURSES: 'ERR_NUMBER_OF_COURSES',
  ERR_TOTAL_CREDITS: 'ERR_TOTAL_CREDITS',
  ERR_INVALID_PROGRAM: 'ERR_INVALID_PROGRAM',
  ERR_PROGRAM_NOT_FOUND: 'ERR_PROGRAM_NOT_FOUND',
  ERR_COURSE_GROUP_NOT_FOUND: 'ERR_COURSE_GROUP_NOT_FOUND',
  ERR_COURSE_NOT_FOUND: 'ERR_COURSE_NOT_FOUND',
  ERR_NUMBER_FORMAT: 'ERR_NUMBER_FORMAT',
  ERR_PAYMENT_FAILED: 'ERR_PAYMENT_FAILED',
  ERR_USER_ALREADY_ENROLLED_IN_SAME_PROGRAM: 'ERR_USER_ALREADY_ENROLLED_IN_SAME_PROGRAM',
  ERR_STUDENT_ENROLLED_IN_CURRENT_PROGRAM: 'ERR_STUDENT_ENROLLED_IN_CURRENT_PROGRAM',
  ERR_COURSE_GROUP_ITEM_EXIST_FOR_COURSE: 'ERR_COURSE_GROUP_ITEM_EXIST_FOR_COURSE',
  ERR_COURSE_GROUP_ITEM_EXIST_FOR_COURSE_GROUP: 'ERR_COURSE_GROUP_ITEM_EXIST_FOR_COURSE_GROUP',
  ERR_COURSE_EXIST_FOR_SUBJECT: 'ERR_COURSE_EXIST_FOR_SUBJECT',
  ERR_PROGRAM_TRANSCRIPT_EXIST_FOR_TRANSCRIPT_TEMPLATE:
    'ERR_PROGRAM_TRANSCRIPT_EXIST_FOR_TRANSCRIPT_TEMPLATE',
  ERR_COURSE_GROUP_EXIST_FOR_PROGRAM: 'ERR_COURSE_GROUP_EXIST_FOR_PROGRAM',
  ERR_RECEIVED_GRADE_IS_GREATER_THAN_OR_EQUAL_TO_PASSING_GRADE:
    'ERR_RECEIVED_GRADE_IS_GREATER_THAN_OR_EQUAL_TO_PASSING_GRADE',
  ERR_RECEIVED_GRADE_IS_LESSER_THAN_PASSING_GRADE:
    'ERR_RECEIVED_GRADE_IS_LESSER_THAN_PASSING_GRADE',
  ERR_INVALID_GRADE_RANGE: 'ERR_INVALID_GRADE_RANGE',
}

export const mapFieldErrors = function (errors) {
  const err = {}
  Object.keys(errors).forEach((key) => {
    const code = errors[key][0] || ''
    const splitted = code.split(':')
    Object.keys(ERROR_CODES_400S).every((code) => {
      if (splitted[0] === code) {
        err[key] = `error:${ERROR_CODES_400S[code].toLocaleLowerCase()}`
        return false
      }
      return true
    })
  })
  return err
}

export const mapGeneralErrors = function (error, defaultMessage) {
  let err = defaultMessage
  Object.keys(ERROR_CODES_400S).every((code) => {
    if (error === code) {
      err = `error:${ERROR_CODES_400S[code].toLocaleLowerCase()}`
      return false
    }
    return true
  })
  return err
}
