export const environmentBaseUrls = {
  development: 'https://sis-api.stpldevs.com',
  redirectBase: 'https://sis-admin.stpldevs.com',
  chat: '',
}

export const API = {
  AUTH: {
    LOGIN: `/account/api/auth/login`,
    REGISTER: `/account/api/auth/register`,
    FORGOTPASSWORD: `/account/api/auth/passwordreset`,
  },
  CORE: {
    SLUG: '/sis-core/api/',
    MASTER: '/sis-core/api/enums',
    DISTRICT: '/sis-core/district',
    SCHOOL: '/sis-core/school',
    GRADESCALE: '/sis-core/grade',
    COURSES: '/sis-core/course',
    COURSE_PROGRAM: '/sis-core/course-program',
    METADATA: '/sis-core/meta-data',
    METADATAOPEN: '/sis-core/api/general-info/meta-data-school',
    SECURITYQUESTIONS: '/sis-core/api/security-question',
    CUSTOMER: `/sis-core/customer`,
    ADMINUSER: `/sis-core/admin`,
    PROGRAM: `/sis-core/program-category`,
    SUBJECT: `/sis-core/subject`,
    TRANSCRIPT: `/sis-core/transcript`,
    COURSEGROUPITEM: '/sis-core/course-group-item',
    ENROLLMENTCOURSE: '/sis-core/enrollment-course',
    ASSIGNCOURSE: '/sis-core/assign-course',
    ENROLLMENT: '/sis-core/enrollment',
    ENROLLMENTPAYMENT: `/sis-core/transaction`,
    ENROLLMENTNOTE: `/sis-core/student-note`,
    ENROLLMENTSUCCESSCOACH: `/sis-core/success-coach`,
    SUCCESSCOACH: `/sis-core/api/success-coach`,
    ENROLLMENTSTATUS: `/sis-core/enrollment-status`,
    REPORTS: `/sis-core/report`,
    GETCONFIGLMSLIST: '/sis-core/lms/master/config',
    GETLMSLIST: '/sis-core/lms/school',
    CREATELMS: '/sis-core/lms/school',
    UPDATELMS: '/sis-core/lms/school',
    DELETELMS: '/sis-core/lms/school',
    AUTHLMS: '/sis-core/lms/auth/school',
    AUTHACCESSCODE: '/sis-core/lms/auth/school',
    DOWNLOADTRANSCRIPT: '/sis-core/api/download-pdf',
  },
  NOTIFICATION: {
    processor: `/communicationv2/-/processors`,
    topics: `/communicationv2/-/topics`,
  },
  APPLICATION: `customercore/-/realms`,
  EMAIL: `/sis-core/email`,
  AUDIT: `auditing/-/`,
  MDS: '/mds/',
  MEDIA: '/media-manager/-/spaces/',
  MEDIARESPONSE: '/media-manager/api/access/',
  PROGRAMS: '/sis-core/',
  PAYMENT: {
    APPID: 'payment/-/admin/app_master',
    GATEWAYMASTERLIST: 'payment/-/admin/gateway_master',
    GATEWAYLIST: 'payment/-/admin/gateway',
    WALLET: 'payment/-/admin/wallet',
    WALLETTRANSACTION: 'payment/-/admin/transactions/wallet',
  },
  ORGANIZATION: `/sis-core/organization-by-urns`,
  AGM: {
    PLATFORMROLES: '/account/-/roles/platform',
    CUSTOMROLES: '/account/-/roles/custom',
    SERVICEROLES: '/account/-/roles/service',
    SERVICEADMINROLES: '/account/-/roles/service-admins',
    RESOURCES: '/account/-/resources',
    USERS: '/account/-/users',
    ENTITIES: '/account/-/entities',
  },
  AGM2: {
    ROLES: '/agm/roles',
    USERS: '/agm/users',
    ACTIONS: '/actionsvc/actions',
    REFRESH: `/authgateway/api/token`,
    INTROSPECT: '/agm/introspect/self',
  },
  MEDIAMANAGER: {
    MEDIA: '/media-manager',
  },
  PROGRAM: `/sis-core/`,
  COURSE: `/sis-core/course-group`,
  TEMPLATE: `/templates/-/`,
  DASHBOARD: `dashboard/-/dashboard`,
}
